// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/activity-user/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/activity-user/[id]').default>>>>
    }
    '/api/activity-user': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/activity-user/index.post').default>>>>
    }
    '/api/activity': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/activity/index.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/activity/index.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/activity/index').default>>>>
    }
    '/api/activity/parent': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/activity/parent').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/session': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/session').default>>>>
    }
    '/api/user/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/[id]').default>>>>
    }
    '/api/user': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/index.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/index.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}